### ISSUE TITLE
Screenshot clipboard functionality doesn't work after updating the system

### ISSUE THREAD

**Issue by savorocks** [thenaterhood/gscreenshot#141]
Hi,

I was using gscreenshot mainly with `gscreenshot -sc` bound to keyboard shortcut so i can quickly select a part of my screen, have it copied on the clipboard and then pasted it wherever I needed it (chat applications or photo editing software, for example).

After recent arch update that functionality is no longer there. I invoke gscreenshot as before, select the region, and when i try to paste somewhere it's like i didn't take the screenshot at all (some previous things would appear, like text copied from the browser etc.).

I should mention that I have xclip installed.
My operating system is Arch Linux.

**Comment by thenaterhood** [comment]
Oh no! Thanks for the report. I'm also on Arch but it seems to be working okay on my system. Here are a few pieces of information that would help me:

- What Python version are you using?
- What desktop environment are you using?
- If you run `gscreenshot -sc` from the command line and take a screenshot, do you get any console output?
- After running `gscreenshot -sc` and taking a screenshot, does xclip show up in your running processes?

**Comment by savorocks** [comment]
Thanks, I'm glad I've been of help.

Just out of curiosity, can you describe what was the problem?

**Comment by thenaterhood** [comment]
I accidentally dropped an exception type when I shuffled some code around. Fixing that led me to a couple other issues as well.

I've also fixed the unit tests so they should catch this before I do a release if it gets broken again.
