### ISSUE TITLE
SPDX license identifier for gscreenshot

### ISSUE THREAD

**Issue by icp1994** [thenaterhood/gscreenshot#166]
Hi, would you like `gscreenshot` to be distributed by distros under `GPL-2.0-only` or `GPL-2.0-or-later` license?

**Comment by thenaterhood** [comment]
Hey @icp1994, thanks for asking! gscreenshot should currently be GPL-2.0-only.

The original version of gscreenshot from 2006 carried the GPL-2.0 license file and didn't specify anything otherwise, so that's what I've been sticking with.

**Comment by icp1994** [comment]
Good to know!
