### ISSUE TITLE
Add screen darkening when screenshot the selection

### ISSUE THREAD

**Issue by BeliyDot** [thenaterhood/gscreenshot#186]
Would be great to darken the screen when you're screenshoting by selection to show more clearly, that you're taking a screenshot. And the area that you select should be without darkening to differentiate it from the other stuff.

**Comment by thenaterhood** [comment]
Yep, should be doable :+1:

**Comment by thenaterhood** [comment]
Added in v3.5.1. I've made the highlight for the selection brighter - it was easier to do that than to darken the rest of the screen.
