### ISSUE TITLE
Bug: Taking screenshot of selection covers entire screen in white on i3

### ISSUE THREAD

**Issue by cptlobster** [thenaterhood/gscreenshot#201]
When using the selection tool to take a screenshot, the entire screen area is initially covered in an opaque white overlay. Hovering over a window covers only that window. When I click/drag, it disappears and the region I'm selecting is covered. While I believe that the box is intended to show up, I don't think the full opacity is intended, and it makes it difficult to see what I'm selecting.

# Video

In the following video, I have vim open as an example for the hover behavior. I opened gscreenshot, clicked the "Selection" tool, and then moved between vim and i3bar. Then, I closed vim, and started another selection. I made a selection, which took the screenshot successfully.

https://github.com/user-attachments/assets/53d0668b-3545-47bb-9bf8-aa0439705fa9

# Version info
- OS: Arch Linux
- Kernel: Linux 6.10.5-arch1-1
- WM: i3 4.23
- `gscreenshot --version` results:
  ```
  Using scrot screenshot backend
  gscreenshot 3.6.2; A simple screenshot tool supporting multiple backends.
  Available features: Region Selection (slop), Window Selection (slop), Cursor Capture (gscreenshot), Full Screen Capture (scrot), Alternate Cursor (gscreenshot), Reuse Region (slop)
  https://github.com/thenaterhood/gscreenshot
  ```

**Comment by thenaterhood** [comment]
Interestingly you're actually not the first I've heard of this one, though I can't reproduce it. There must be a particular compositor setup that causes it.

It's on my radar to fix, I just need to think about how to do it since it seems to be a fairly unusual problem.

**Comment by cptlobster** [comment]
> There must be a particular compositor setup that causes it.

I didn't realize this, but I wasn't actually starting a compositor. I thought it was in my i3config but it must not be part of the default (generated by i3-config-wizard) or I might have accidentally deleted it. When I start `picom` manually, the transparency works as intended.

so yes, I suppose the "particular compositor setup" is no compositor at all. Probably not much you can do about transparency without a compositor, so this bug is likely just user error.
