### ISSUE TITLE
Missing dependency, and something else

### ISSUE THREAD

**Issue by shish** [thenaterhood/gscreenshot#205]
Looks like there's a missing dependency on python-dbus (not sure if that's optional or required)
```
$ yay -S gscreenshot
[...]
Optional dependencies for gscreenshot
    xclip: command line clipboard support
    xdg-utils: for opening screenshot files from gscreenshot [installed]
    pandoc: for generating the manpage at build (or use go-md2man)
    go-md2man: for generating the manpage at build (or use pandoc)
    slurp: for region selecton on Wayland
    wl-clipboard: Wayland clipboard support
```

```
$ gscreenshot
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/gscreenshot/screenshooter/xdg_desktop_portal.py", line 150, in <module>
    XdgPortalScreenshot().request()
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gscreenshot/screenshooter/xdg_desktop_portal.py", line 49, in __init__
    raise NoSupportedScreenshooterError('python-dbus is unavailable')
```

But things aren't working even after it is installed :(

```
$ yay -S python-dbus
[...]
:: Processing package changes...
(1/1) installing python-dbus                                                                [######################################################] 100%
Optional dependencies for python-dbus
    python-gobject: D-Bus services via PyGI [installed]
```

```
$ gscreenshot
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dbus/connection.py", line 218, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/gscreenshot/screenshooter/xdg_desktop_portal.py", line 109, in callback
    sys.exit(1)
SystemExit: 1
```

How do I debug "SystemExit: 1"? x_x

**Comment by thenaterhood** [comment]
python-dbus should be listed as an optional dependency, you're absolutely correct. It's required if you're using the XDG desktop portal backend for screenshots, but not for other configurations.

The second issue I have not seen before. That's due to the XDG desktop portal throwing an error when taking a screenshot, though I don't know more than that. I'll do some research and see if I can improve that error message to be more helpful.

In the meantime, what desktop environment are you using?

**Comment by thenaterhood** [comment]
Check out https://github.com/thenaterhood/gscreenshot/releases/tag/v3.6.3 (also in the AUR), which will hopefully surface a slightly better error

**Comment by shish** [comment]
3.6.3 (with python-dbus) works, so whatever was causing the SystemExit seems to be fixed \o/

(Just in case it's relevant in the future, I'm using a somewhat duct-taped Arch install - I wanted to use Sway on Debian, but Sway by itself lacks a lot of features, and all of the third-party sway add-ons were in the AUR and nowhere else, so I switched to Arch. I started with a bare-minimum command line install, then have been installing one package at a time to fix missing things (like fonts and screenshots), as opposed to installing a complete desktop environment bundle)

**Comment by thenaterhood** [comment]
As a fellow Arch user, I thought the duct tape was a feature :thinking: 

Glad it's working!
