### ISSUE TITLE
No preview

### ISSUE THREAD

**Issue by pavroo** [thenaterhood/gscreenshot#4]
Hi
I just tried version 2.3.1.
It takes screenshot fine, but it does not make a preview in the application window.

Edit
And building package (with dpkg-buildpackage command) doesn't copy .desktop and .png files too.

**Comment by thenaterhood** [comment]
Thanks for the heads up! I'll look into those. 

Could you let me know what version of Python you ran it on and if it gives any output if you run gscreenshot from the command line?

**Comment by pavroo** [comment]
Python 3.5.1, and rest of the packages versions the same as in Debian testing repos.

The output:

pavroo@a2t2:~$ gscreenshot

(gscreenshot:16337): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed

(gscreenshot:16337): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by thenaterhood** [comment]
Thanks! That's odd, I haven't encountered that issue before. I just pushed a commit that should fix the missing preview, 29685e8. I'll put up a new release in a little while.

I'll look more into the missing icon and .desktop, but that may need to be done on the packaging side. Python's setuptools/distutils don't like to install files outside of Python's install path. In the ArchLinux user repositories I have:

```
        install -Dm644 dist/$pkgname.desktop \
            "$pkgdir/usr/share/applications/$pkgname.desktop"
        install -Dm644 dist/black-white_2-Style-applets-screenshooter.png \
            "$pkgdir/usr/share/pixmaps/$pkgname.png"
```

which makes sure the icon and .desktop are placed in the package. I suppose I could add a helper script to take care of that as well.

**Comment by thenaterhood** [comment]
I found a way that's not too bad for installing the data files with the setup.py script. I have it here: https://github.com/thenaterhood/gscreenshot/archive/install-desktop.tar.gz. I haven't changed the version numbers, so that will install as v2.3.2.

Try it out and let me know how it works. If it's good, I'll create a release for it which will be v2.3.3.

**Comment by pavroo** [comment]
It's perfect now. The preview works, and the 2 files are copied to a deb.
What I would ask you is adding /usr/share/menu/gscreenshot file to the package too.
[gscreenshot.zip](https://github.com/thenaterhood/gscreenshot/files/222844/gscreenshot.zip)


.

**Comment by thenaterhood** [comment]
Great! All taken care of. https://github.com/thenaterhood/gscreenshot/releases/tag/v2.3.3.

**Comment by thenaterhood** [comment]
Eh, forgot to bump the version again, give me one sec.

**Comment by thenaterhood** [comment]
Alright, all good, release updated.

**Comment by pavroo** [comment]
Cool !
It's in Sparky repos now.
