### ISSUE TITLE
Missing/incorrect requires and buildrequires in RPM spec

### ISSUE THREAD

**Issue by axk4545** [thenaterhood/gscreenshot#52]
When attempting to install the RPM on Fedora 25 it fails with the error `nothing provides /bin/python3`
The spec file is missing BuildRequires and may be missing Requires. 
See https://fedoraproject.org/wiki/Packaging:Python for guidelines

**Comment by thenaterhood** [comment]
This is due to dnf/yum not being smart enough to correctly recognize symlinks. Python3 was listed as a requirement, but because the package was built with /bin/python3, dnf was not willing to accept it.

This is now fixed in 2.6.3-2 on the RPM repo.
