### ISSUE TITLE
Copy to clipboard for gscreenshot-cli

### ISSUE THREAD

**Issue by mahdiG** [thenaterhood/gscreenshot#53]
Hi. Please add copy to clipboard option for gscreenshot-cli.

**Comment by thenaterhood** [comment]
Good idea! I think I should be able to make this happen.

I think right now, copy to clipboard is powered by GTK amd I'd like to avoid tying the cli to GTK. A little research might need to happen is all though.

**Comment by thenaterhood** [comment]
Coming up soon! Changes are in #54 and will be in the next release.

**Comment by thenaterhood** [comment]
Available now! https://github.com/thenaterhood/gscreenshot/releases/tag/v2.7.0
