### ISSUE TITLE
gscreenshot-cli aborts selection capture on keyboard press

### ISSUE THREAD

**Issue by mahdiG** [thenaterhood/gscreenshot#57]
Hi. When I run `gscreenshot-cli -s -c` and press a keyboard key to switch to another window it shows this:
```
Failed to call region selector -- Using fallback region selection
Key was pressed, aborting shot
giblib error: no image grabbed
Traceback (most recent call last):
  File "/usr/local/bin/gscreenshot-cli", line 11, in <module>
    load_entry_point('gscreenshot==2.7.0', 'console_scripts', 'gscreenshot-cli')()
  File "/usr/local/lib/python2.7/dist-packages/gscreenshot/frontend/cli.py", line 120, in main
    run()
  File "/usr/local/lib/python2.7/dist-packages/gscreenshot/frontend/cli.py", line 111, in run
    gscreenshot.save_last_image(tmp_file)
  File "/usr/local/lib/python2.7/dist-packages/gscreenshot/__init__.py", line 159, in save_last_image
    image.save(filename, actual_file_ext.upper())
AttributeError: 'NoneType' object has no attribute 'save'

```
It's good that it only aborts shot on ESC button and captures on click.

**Comment by thenaterhood** [comment]
Nice find! I'll check on that later today. I think I forgot to handle
cancelling the selection somewhere along the way.

Esc should cancel the selection, but shouldn't be quite so ugly :).

**Comment by mahdiG** [comment]
By the way, I also noticed this happens when the GUI too.

**Comment by thenaterhood** [comment]
This will be in the next release, which I expect will be 2.7.1. Should be coming in the very near future.

**Comment by mahdiG** [comment]
Hi. I updated to 2.7.1 today and the problem still exists with the difference that it now only shows:
```
Failed to call region selector -- Using fallback region selection
Key was pressed, aborting shot
giblib error: no image grabbed

```
I think I didn't explain well what I meant. I run `gscreenshot-cli -s -c` in terminal and then want to switch to another window using keyboard shortcut to take a screenshot. The shortcut to change window is Super+Tab but as soon as I press Super (or any other key) the app closes with the above message.
In this case the only window I can take screenshot of is the Terminal.
The app should only abort shot on ESC key press and no other keys.

**Comment by thenaterhood** [comment]
Ahh, I gotcha. You're using scrot's selection tool which quits out if you hit a key, which is unfortunately out of my control. Slop (an alternate selection tool that gscreenshot will use if you have it installed) has the option to ignore keypresses, which I can add in.

A workaround in the meantime to use a couple second delay. Gscreenshot will have you select a region or window right away, then will wait for your delay before taking a screenshot. It's not super smooth, but it'll get you there.

The way I do it is I have `gscreenshot-cli -s -c` bound to a keystroke.
