### ISSUE TITLE
[feature request] Add open with dropdown

### ISSUE THREAD

**Issue by Iambecomeroot** [thenaterhood/gscreenshot#60]
First off, thanks for the amazing app. It works great!

However, one thing I find myself doing quite frequently is doing a selection then clicking open to open it in eye of gnome just to use eog's "open with" dropdown to open it with gimp. I don't want change my default image viewer to gimp. Would it be possible to add an "open with" dropdown?

**Comment by thenaterhood** [comment]
Thanks for the feedback!

I think adding an "open with" option shouldn't be a big deal.

**Comment by thenaterhood** [comment]
I've released 2.8.0 (https://github.com/thenaterhood/gscreenshot/releases/tag/v2.8.0) which adds an open-with option to the dropdown. It'll be in the AUR shortly.

There's likely some refinements that can be made to it, but that's what iteration is for.

**Comment by Iambecomeroot** [comment]
Awesome! I am patiently waiting for it to show up in the AUR.

**Comment by Iambecomeroot** [comment]
Working great. Thanks a bunch.
