### ISSUE TITLE
Be able to change the -f argument filename default path

### ISSUE THREAD

**Issue by faurehu** [thenaterhood/gscreenshot#79]
I use gscreenshot-cli with i3 key bindings. If I bind -f with a path then all my clips will have the same name and they'll replace each other.

It'd be nice if I could edit the path of the file without specifying the file name.

**Comment by thenaterhood** [comment]
I agree, good idea!

I could see allowing the `-f` option to accept both a full filename, and just a directory. Shouldn't be too much of a problem to implement.

**Comment by thenaterhood** [comment]
This will be part of the next gscreenshot release. The `-f` option will accept both a full filename, or just a path. If given just a path, it will use the default time-based naming scheme for files, and will put them in that path, creating the directory tree as needed.

**Comment by faurehu** [comment]
Thank you very much for your work @thenaterhood
