### ISSUE TITLE
Copy to clipboard in Gui Version

### ISSUE THREAD

**Issue by nichxx** [thenaterhood/gscreenshot#95]
when i copy the screenshot to clipboard in gui version if i close the interface i can't paste the image
with gscreenshot-cli no problem

**Comment by thenaterhood** [comment]
Interesting! Could you let me know more about your environment? I'm interested to know your gscreenshot version, desktop environment, and that sort of thing.

**Comment by nichxx** [comment]
Archlinux
i3-gaps as windows manager
gscreenshot installed from AUR

aur/gscreenshot 2.12.0-1 [installed] [18+] [0.01%] [6 Feb 2020]

**Comment by thenaterhood** [comment]
I suspect I know what the problem is, and I think #98 will fix it.

Normally, the gscreenshot GUI will use the native GTK clipboard. I think that for whatever reason your clipboard doesn't fully support persistence. What I've changed is that gscreenshot will check for that and if it doesn't support it, it will use xclip like the command line does.

If you're comfortable with python, feel free to take that out for a spin and let me know if it helps.

**Comment by nichxx** [comment]
i'm sorry but i'm not able with python and coding generally, i tried to install last release from git but i have the same result.

**Comment by thenaterhood** [comment]
We'll get it sorted. It's most likely a fixable gscreenshot problem. Firefox, Gimp, and the like have been around a while longer and have had time to get these things right.

If you're not comfortable or able to do the following, that's okay! We can see if the next release of gscreenshot fixes the problem, and if it doesn't we can try some more things.

This is a Python snippet that will give me more information (I want to see what Python sees here). You can either paste it into a file and run it with `python yourfile` or you can open the Python interpreter (just run `python` in the terminal) and paste it. Copy what you get into a comment here.

```
from gi import pygtkcompat
pygtkcompat.enable()
pygtkcompat.enable_gtk(version='3.0')

from gi.repository import Gtk, Gdk

display = Gdk.Display.get_default()
print("Supports clipboard persistence: %d" % display.supports_clipboard_persistence())
```

**Comment by nichxx** [comment]
Supports clipboard persistence: 0

**Comment by nichxx** [comment]
I downloaded the right commit and now work fine.
Thank you

**Comment by thenaterhood** [comment]
Perfect! :)

There will be a release in the next few days that will make it into the AUR. Thanks for the help tracking this down!
